### ISSUE TITLE
并发环境下获取容器可能导致类转换异常 “cn.crane4j.core.container.MethodInvokerContainer cannot be cast to cn.crane4j.core.container.ContainerDefinition”

### ISSUE THREAD

**Issue by urzeye** [opengoofy/crane4j#162]
# 问题描述
业务中有一个新建业务对象的场景，需要在新建完成后，立刻查询新建对象的信息和其关联的其他业务信息（两个接口，其中一个使用了 `@AutoOperate`注解，一个使用了`operateTemplate.execute()`方法），前端在联调过程中发现两个接口偶发的、交替性、无规律地出现运行时异常 `cn.crane4j.core.container.MethodInvokerContainer cannot be cast to cn.crane4j.core.container.ContainerDefinition` ，其中一个加上延时问题即得到解决。
![image](https://github.com/opengoofy/crane4j/assets/20869204/4ac641dc-a680-4ec1-9a78-0ccc8c50dbe6)

# 异常堆栈
```
cn.crane4j.core.container.MethodInvokerContainer cannot be cast to cn.crane4j.core.container.ContainerDefinition
java.lang.ClassCastException: cn.crane4j.core.container.MethodInvokerContainer cannot be cast to cn.crane4j.core.container.ContainerDefinition
	at cn.crane4j.core.container.DefaultContainerManager.lambda$getContainer$1(DefaultContainerManager.java:155)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1877)
	at cn.crane4j.core.container.DefaultContainerManager.getContainer(DefaultContainerManager.java:149)
	at cn.crane4j.extension.spring.Crane4jApplicationContext.getContainer(Crane4jApplicationContext.java:134)
	at cn.crane4j.core.executor.BeanOperationExecutor$Options.getContainer(BeanOperationExecutor.java:81)
	at cn.crane4j.core.executor.AbstractBeanOperationExecutor.createAssembleExecution(AbstractBeanOperationExecutor.java:151)
	at cn.crane4j.core.executor.AbstractBeanOperationExecutor.lambda$null$2(AbstractBeanOperationExecutor.java:127)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at cn.crane4j.core.executor.AbstractBeanOperationExecutor.lambda$execute$3(AbstractBeanOperationExecutor.java:128)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at cn.crane4j.core.executor.AbstractBeanOperationExecutor.execute(AbstractBeanOperationExecutor.java:124)
	at cn.crane4j.core.executor.BeanOperationExecutor.execute(BeanOperationExecutor.java:46)
	at cn.crane4j.core.support.OperateTemplate.execute(OperateTemplate.java:168)
	at cn.crane4j.core.support.OperateTemplate.execute(OperateTemplate.java:76)
	at com.company.label.management.service.impl.LabelValueServiceImpl.buildEnumTree(LabelValueServiceImpl.java:153)
	at com.company.label.management.service.impl.LabelValueServiceImpl$$FastClassBySpringCGLIB$$87148bdd.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at com.baomidou.dynamic.datasource.aop.DynamicDataSourceAnnotationInterceptor.invoke(DynamicDataSourceAnnotationInterceptor.java:50)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
	at com.company.label.management.service.impl.LabelValueServiceImpl$$EnhancerBySpringCGLIB$$f22125f9.buildEnumTree(<generated>)
	at com.company.label.management.controller.LabelValueController.buildEnumTree(LabelValueController.java:90)
	at com.company.label.management.controller.LabelValueController$$FastClassBySpringCGLIB$$f9e06cb1.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:123)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
	at com.company.label.management.controller.LabelValueController$$EnhancerBySpringCGLIB$$9b58419b.buildEnumTree(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:114)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Createsequence** [comment]
研究了一下，发现在并发情况下确实存在这个问题。

首先，cranej4 中的容器实际上都是懒加载的，当一开始把容器注册到 `ContainerManager` 的时候，实际上注册的是类似 Spring 的 `ObjectFactory` 的定义对象 `ContainerDefinition`，然后等到通过 `getContainer` 获取的时候，才会通过定义对象创建容器实例，最后再替换掉原本的工厂对象缓存。

因此，在正常情况下，通过 `getContainer` 获得容器时，会获取 namespace 对应的缓存：
- 第一步，先检查缓存是否已经是容器实例，如果是直接返回，不是则进入第二步；
- 第二步，由于缓存的是定义对象，因此根据定义对象创建容器实例，然后再使用该替换掉原本的定义对象缓存；

![a5207b7d65c2bbad0dabe98de5a5478](https://github.com/opengoofy/crane4j/assets/49221670/fedcb0e7-f748-4a52-89ed-153d49a858f4)

问题就出在第二步上，假设现在有一个线程 A，它执行了第一步后，判断缓存中的仍然还是定义对象，因此就会进入第二步，尝试创建容器。但是在这个时候，另一个线程 B 抢先完成了第二步，缓存中的定义对象已经被替换为容器实例，但是此时 A 线程依然还以为缓存中的是定义对象，然后就会在执行 `(ContainerDefinition) t` 的时候抛出异常。

这个问题需要修改第 152 行的判断 `isRegistered && contaienr instanceof Container`，将其改为 `isRegistered && t instanceof Container`。晚点我会尽快修复并发版，如果比较赶，也可以继承 `Crane4jApplicationContext`，然后重写 `getContainer` 方法修改此处的 if 判断，最后把子类放到Spring容器里即可。

**Comment by Createsequence** [comment]
已在 https://github.com/opengoofy/crane4j/pull/163 修复，明天在 2.1.2 把它发上去。
